#!/bin/sh

xset r rate 300 50 
setxkbmap -layout us -variant intl -option ctrl:nocaps 
xcape -e "Control_L=Escape"
xset s off -dpms 

redshift -l -33.45694:-70.64827 -t 5700:2600 -b 1.0:0.7 -g 0.9 -m randr -v &
xwallpaper --zoom ~/Public/img/os/solid_green.png &
